// packages/web-components/fast-components-msft/src/checkbox/index.ts
import { customElement } from "@microsoft/fast-element";
import { Checkbox, CheckboxTemplate as template } from "@microsoft/fast-components";
import { CheckboxStyles as styles } from "./checkbox.styles";

@customElement({
    name: "msft-checkbox",
    template,
    styles,
})
export class MSFTCheckbox extends Checkbox {}

// packages/fast-components-react-msft/src/checkbox/index.ts
import * as React from "react";
import {
    Checkbox,
    ICheckboxClassNameContract,
    ICheckboxHandledProps,
    ICheckboxUnhandledProps,
    IFoundationProps
} from "@microsoft/fast-components-react-base";
import manageJss from "@microsoft/fast-jss-manager-react";
import {CheckboxStyles} from "@microsoft/fast-components-styles-msft";

export default manageJss(CheckboxStyles)(Checkbox);
