// packages/fast-components-react-msft/src/divider/index.ts
import * as React from "react";
import { Divider, IDividerClassNameContract, IDividerProps, IFoundationProps } from "@microsoft/fast-components-react-base";
import manageJss from "@microsoft/fast-jss-manager-react";
import {DividerStyles} from "@microsoft/fast-components-styles-msft";

export default manageJss(DividerStyles)(Divider);

// packages/web-components/fast-components/src/divider/index.ts
import { customElement } from "@microsoft/fast-element";
import { Divider, DividerTemplate as template } from "@microsoft/fast-foundation";
import { DividerStyles as styles } from "./divider.styles.js";

@customElement({
    name: "fast-divider",
    template,
    styles,
})
export class FASTDivider extends Divider {}
