// packages/fast-components-react-msft/src/text-field/index.ts
import * as React from "react";
import {
    IFoundationProps,
    ITextfieldClassNameContract,
    ITextfieldHandledProps,
    ITextfieldManagedClasses,
    ITextfieldUnhandledProps,
    TextField
} from "@microsoft/fast-components-react-base";
import manageJss, { IJSSManagerProps } from "@microsoft/fast-jss-manager-react";
import { IDesignSystem, TextfieldStyles } from "@microsoft/fast-components-styles-msft";

export default manageJss(TextfieldStyles)(TextField);

// packages/web-components/fast-components-msft/src/text-field/index.ts
import { customElement } from "@microsoft/fast-element";
import { TextFieldTemplate as template, TextField } from "@microsoft/fast-components";
import { TextFieldStyles as styles } from "./text-field.styles.js";

@customElement({
    name: "msft-text-field",
    template,
    styles,
})
export class MSFTTextField extends TextField {}
