// packages/web-components/fast-foundation/src/dialog/dialog.js
var __decorate =
    (this && this.__decorate) ||
    function (decorators, target, key, desc) {
        var c = arguments.length,
            r =
                c < 3
                    ? target
                    : desc === null
                    ? (desc = Object.getOwnPropertyDescriptor(target, key))
                    : desc,
            d;
        if (typeof Reflect === "object" && typeof Reflect.decorate === "function")
            r = Reflect.decorate(decorators, target, key, desc);
        else
            for (var i = decorators.length - 1; i >= 0; i--)
                if ((d = decorators[i]))
                    r = (c < 3 ? d(r) : c > 3 ? d(target, key, r) : d(target, key)) || r;
        return c > 3 && r && Object.defineProperty(target, key, r), r;
    };
import { attr, DOM } from "@microsoft/fast-element";
import { keyCodeEscape, keyCodeTab } from "@microsoft/fast-web-utilities";
import { isTabbable } from "tabbable";
import { FoundationElement } from "../foundation-element";
/**
 * A Switch Custom HTML Element.
 * Implements the {@link https://www.w3.org/TR/wai-aria-1.1/#dialog | ARIA dialog }.
 *
 * @public
 */
export class Dialog extends FoundationElement {
    constructor() {
        super(...arguments);
        /**
         * Indicates the element is modal. When modal, user interaction will be limited to the contents of the element.
         * @public
         * @defaultValue - true
         * @remarks
         * HTML Attribute: modal
         */
        this.modal = true;
        /**
         * The hidden state of the element.
         *
         * @public
         * @defaultValue - false
         * @remarks
         * HTML Attribute: hidden
         */
        this.hidden = false;
        /**
         * Indicates that the dialog should trap focus.
         *
         * @public
         * @defaultValue - true
         * @remarks
         * HTML Attribute: trap-focus
         */
        this.trapFocus = true;
        this.trapFocusChanged = () => {
            if (this.trapFocus) {
                // Add an event listener for focusin events if we should be trapping focus
                document.addEventListener("focusin", this.handleDocumentFocus);
                // determine if we should move focus inside the dialog
                if (this.shouldForceFocus(document.activeElement)) {
                    this.focusFirstElement();
                }
            } else {
                // remove event listener if we are not trapping focus
                document.removeEventListener("focusin", this.handleDocumentFocus);
            }
        };
        this.handleDocumentKeydown = e => {
            if (!e.defaultPrevented && !this.hidden) {
                switch (e.keyCode) {
                    case keyCodeEscape:
                        this.dismiss();
                        e.preventDefault();
                        break;
                    case keyCodeTab:
                        this.handleTabKeyDown(e);
                        break;
                }
            }
        };
        this.handleDocumentFocus = e => {
            if (!e.defaultPrevented && this.shouldForceFocus(e.target)) {
                this.focusFirstElement();
                e.preventDefault();
            }
        };
        this.handleTabKeyDown = e => {
            if (!this.trapFocus || this.hidden) {
                return;
            }
            const bounds = this.getTabQueueBounds();
            if (bounds.length === 0) {
                return;
            }
            if (bounds.length === 1) {
                // keep focus on single element
                bounds[0].focus();
                e.preventDefault();
                return;
            }
            if (e.shiftKey && e.target === bounds[0]) {
                bounds[bounds.length - 1].focus();
                e.preventDefault();
            } else if (!e.shiftKey && e.target === bounds[bounds.length - 1]) {
                bounds[0].focus();
                e.preventDefault();
            }
            return;
        };
        this.getTabQueueBounds = () => {
            const bounds = [];
            return Dialog.reduceTabbableItems(bounds, this);
        };
        /**
         * focus on first element of tab queue
         */
        this.focusFirstElement = () => {
            const bounds = this.getTabQueueBounds();
            if (bounds.length > 0) {
                bounds[0].focus();
            }
        };
        /**
         * we should only focus if focus has not already been brought to the dialog
         */
        this.shouldForceFocus = currentFocusElement => {
            return !this.hidden && !this.contains(currentFocusElement);
        };
    }
    /**
     * @internal
     */
    dismiss() {
        this.$emit("dismiss");
    }
    /**
     * The method to show the dialog.
     *
     * @public
     */
    show() {
        this.hidden = false;
    }
    /**
     * The method to hide the dialog.
     *
     * @public
     */
    hide() {
        this.hidden = true;
    }
    /**
     * @internal
     */
    connectedCallback() {
        super.connectedCallback();
        document.addEventListener("keydown", this.handleDocumentKeydown);
        // Ensure the DOM is updated
        // This helps avoid a delay with `autofocus` elements receiving focus
        DOM.queueUpdate(this.trapFocusChanged);
    }
    /**
     * @internal
     */
    disconnectedCallback() {
        super.disconnectedCallback();
        // remove keydown event listener
        document.removeEventListener("keydown", this.handleDocumentKeydown);
        // if we are trapping focus remove the focusin listener
        if (this.trapFocus) {
            document.removeEventListener("focusin", this.handleDocumentFocus);
        }
    }
    /**
     * Reduce a collection to only its focusable elements.
     *
     * @param elements - Collection of elements to reduce
     * @param element - The current element
     *
     * @internal
     */
    static reduceTabbableItems(elements, element) {
        if (element.getAttribute("tabindex") === "-1") {
            return elements;
        }
        if (
            isTabbable(element) ||
            (Dialog.isFocusableFastElement(element) && Dialog.hasTabbableShadow(element))
        ) {
            elements.push(element);
            return elements;
        }
        if (element.childElementCount) {
            return elements.concat(
                Array.from(element.children).reduce(Dialog.reduceTabbableItems, [])
            );
        }
        return elements;
    }
    /**
     * Test if element is focusable fast element
     *
     * @param element - The element to check
     *
     * @internal
     */
    static isFocusableFastElement(element) {
        var _a, _b;
        return !!((_b =
            (_a = element.$fastController) === null || _a === void 0
                ? void 0
                : _a.definition.shadowOptions) === null || _b === void 0
            ? void 0
            : _b.delegatesFocus);
    }
    /**
     * Test if the element has a focusable shadow
     *
     * @param element - The element to check
     *
     * @internal
     */
    static hasTabbableShadow(element) {
        var _a, _b;
        return Array.from(
            (_b =
                (_a = element.shadowRoot) === null || _a === void 0
                    ? void 0
                    : _a.querySelectorAll("*")) !== null && _b !== void 0
                ? _b
                : []
        ).some(x => {
            return isTabbable(x);
        });
    }
}
__decorate([attr({ mode: "boolean" })], Dialog.prototype, "modal", void 0);
__decorate([attr({ mode: "boolean" })], Dialog.prototype, "hidden", void 0);
__decorate(
    [attr({ attribute: "trap-focus", mode: "boolean" })],
    Dialog.prototype,
    "trapFocus",
    void 0
);
__decorate(
    [attr({ attribute: "aria-describedby" })],
    Dialog.prototype,
    "ariaDescribedby",
    void 0
);
__decorate(
    [attr({ attribute: "aria-labelledby" })],
    Dialog.prototype,
    "ariaLabelledby",
    void 0
);
__decorate([attr({ attribute: "aria-label" })], Dialog.prototype, "ariaLabel", void 0);

// packages/fast-components-react-base/src/dialog/dialog.tsx
import { DialogClassNameContract } from "@microsoft/fast-components-class-name-contracts-base";
import Foundation, { HandledProps } from "@microsoft/fast-components-foundation-react";
import { classNames, keyCodeEscape, keyCodeTab } from "@microsoft/fast-web-utilities";
import { canUseDOM } from "exenv-es6";
import React from "react";
import { DisplayNamePrefix } from "../utilities";
import { DialogHandledProps, DialogProps, DialogUnhandledProps } from "./dialog.props";
import { isFunction, isNil } from "lodash-es";
import Tabbable from "tabbable";

class Dialog extends Foundation<DialogHandledProps, DialogUnhandledProps, {}> {
    public static defaultProps: Partial<DialogProps> = {
        contentHeight: "480px",
        contentWidth: "640px",
        visible: false,
        managedClasses: {},
    };

    public static displayName: string = `${DisplayNamePrefix}Dialog`;

    protected handledProps: HandledProps<DialogHandledProps> = {
        describedBy: void 0,
        label: void 0,
        labelledBy: void 0,
        contentWidth: void 0,
        contentHeight: void 0,
        modal: void 0,
        managedClasses: void 0,
        onDismiss: void 0,
        visible: void 0,
    };

    private rootElement: React.RefObject<HTMLDivElement> = React.createRef<
        HTMLDivElement
    >();

    /**
     * Renders the component
     */
    public render(): React.ReactElement<HTMLDivElement> {
        const {
            dialog_positioningRegion,
            dialog_contentRegion,
        }: DialogClassNameContract = this.props.managedClasses;

        return (
            <div
                ref={this.rootElement}
                {...this.unhandledProps()}
                className={this.generateClassNames()}
                aria-hidden={!this.props.visible}
            >
                <div className={classNames(dialog_positioningRegion)}>
                    {this.renderModalOverlay()}
                    <div
                        role="dialog"
                        tabIndex={-1}
                        className={classNames(dialog_contentRegion)}
                        style={{
                            height: this.props.contentHeight,
                            width: this.props.contentWidth,
                        }}
                        aria-describedby={this.props.describedBy}
                        aria-labelledby={this.props.labelledBy}
                        aria-label={this.props.label}
                    >
                        {this.props.children}
                    </div>
                </div>
            </div>
        );
    }

    /**
     * React life-cycle method
     */
    public componentDidMount(): void {
        if (canUseDOM()) {
            if (this.shouldAddKeyListener(this.props)) {
                document.addEventListener("keydown", this.handleDocumentKeyDown);
            }
            if (this.props.modal) {
                document.addEventListener("focusin", this.handleDocumentFocus);
                if (this.shouldForceFocus(document.activeElement)) {
                    this.focusOnFirstElement();
                }
            }
        }
    }

    /**
     * React life-cycle method
     */
    public componentDidUpdate(prevProps: Partial<DialogHandledProps>): void {
        if (canUseDOM()) {
            if (!prevProps.modal && this.props.modal) {
                document.addEventListener("focusin", this.handleDocumentFocus);
                this.focusOnFirstElement();
            } else if (prevProps.modal && !this.props.modal) {
                document.removeEventListener("focusin", this.handleDocumentFocus);
            }

            if (
                !this.shouldAddKeyListener(prevProps) &&
                this.shouldAddKeyListener(this.props)
            ) {
                document.addEventListener("keydown", this.handleDocumentKeyDown);
            } else if (
                this.shouldAddKeyListener(prevProps) &&
                !this.shouldAddKeyListener(this.props)
            ) {
                document.removeEventListener("keydown", this.handleDocumentKeyDown);
            }
        }
    }

    /**
     * React life-cycle method
     */
    public componentWillUnmount(): void {
        if (canUseDOM()) {
            if (this.shouldAddKeyListener(this.props)) {
                document.removeEventListener("keydown", this.handleDocumentKeyDown);
            }

            if (this.props.modal) {
                document.removeEventListener("focusin", this.handleDocumentFocus);
            }
        }
    }

    /**
     * Generates class names
     */
    protected generateClassNames(): string {
        return super.generateClassNames(classNames(this.props.managedClasses.dialog));
    }

    /**
     * Renders the modal overlay
     */
    private renderModalOverlay(): React.ReactElement<HTMLDivElement> {
        if (!this.props.modal) {
            return;
        }

        return (
            <div
                className={classNames(this.props.managedClasses.dialog_modalOverlay)}
                onClick={this.checkForSoftDismiss}
                onTouchStart={this.checkForSoftDismiss}
                role={"presentation"}
                tabIndex={-1}
                style={{
                    touchAction: "none",
                }}
            />
        );
    }

    /**
     * Check if props demand a key listener
     */
    private shouldAddKeyListener = (props: DialogProps): boolean => {
        if (props.modal || props.onDismiss) {
            return true;
        }
        return false;
    };

    /**
     * handles document key down events
     */
    private handleDocumentKeyDown = (event: KeyboardEvent): void => {
        if (!event.defaultPrevented && this.props.visible) {
            switch (event.keyCode) {
                case keyCodeEscape:
                    this.checkForSoftDismiss(event);
                    break;

                case keyCodeTab:
                    this.handleTabKeyDown(event);
                    break;
            }
        }
    };

    /**
     * Invokes dialog soft dismiss if appropriate
     */
    private checkForSoftDismiss = (
        event: KeyboardEvent | React.MouseEvent | React.TouchEvent
    ): void => {
        if (
            this.props.onDismiss &&
            typeof this.props.onDismiss === "function" &&
            this.props.visible
        ) {
            this.props.onDismiss(event);
        }
    };

    /**
     * process tab key down events
     */
    private handleTabKeyDown = (event: KeyboardEvent): void => {
        if (!this.props.modal) {
            // only handle tab keystrokes when modal
            return;
        }
        const tabbableElements: HTMLElement[] = Tabbable(this.rootElement.current);
        const tabbableElementCount: number = tabbableElements.length;
        if (tabbableElementCount === 0) {
            this.tryFocusOnRootElement();
            event.preventDefault();
            return;
        }
        // intervene in normal tab order for first and last items in list
        if (event.shiftKey && event.target === tabbableElements[0]) {
            tabbableElements[tabbableElementCount - 1].focus();
            event.preventDefault();
        } else if (
            !event.shiftKey &&
            event.target === tabbableElements[tabbableElementCount - 1]
        ) {
            tabbableElements[0].focus();
            event.preventDefault();
        }
    };

    /**
     * forces focus to first tabbable element of modal dialog if document gains focus while dialog is open
     */
    private handleDocumentFocus = (event: FocusEvent): void => {
        if (
            !event.defaultPrevented &&
            this.shouldForceFocus(event.target as HTMLElement)
        ) {
            this.focusOnFirstElement();
            event.preventDefault();
        }
    };

    /**
     * test to avoid forcing focus when focus is already within
     */
    private shouldForceFocus = (currentFocusElement: Element): boolean => {
        if (
            this.props.visible &&
            this.rootElement.current instanceof HTMLElement &&
            !(this.rootElement.current as HTMLElement).contains(currentFocusElement)
        ) {
            return true;
        }
        return false;
    };

    /**
     * focus on first element of tab queue
     */
    private focusOnFirstElement = (): void => {
        if (canUseDOM() && this.rootElement.current instanceof HTMLElement) {
            const tabbableElements: HTMLElement[] = Tabbable(this.rootElement.current);
            if (tabbableElements.length === 0) {
                this.tryFocusOnRootElement();
            } else {
                tabbableElements[0].focus();
            }
        }
    };

    /**
     * if no tabbable elements try to focus root element
     * generally a modal dialog should be expected to have a focusable element
     */
    private tryFocusOnRootElement = (): void => {
        if (this.rootElement.current instanceof HTMLElement) {
            this.rootElement.current.focus();
        }
    };
}

export default Dialog;
export * from "./dialog.props";
export { DialogClassNameContract };
