// packages/web-components/fast-components-msft/src/radio/index.ts
import { customElement } from "@microsoft/fast-element";
import { Radio, RadioTemplate as template } from "@microsoft/fast-components";
import { RadioStyles as styles } from "./radio.styles";

@customElement({
    name: "msft-radio",
    template,
    styles,
})
export class MSFTRadio extends Radio {}

// packages/fast-components-react-msft/src/radio/index.ts
import * as React from "react";
import {
    Radio
} from "@microsoft/fast-components-react-base";
import manageJss, { IJSSManagerProps } from "@microsoft/fast-jss-manager-react";
import { IDesignSystem, RadioStyles } from "@microsoft/fast-components-styles-msft";

export default manageJss(RadioStyles)(Radio);
