// packages/fast-components-react-base/src/dialog/dialog.tsx
import { DialogClassNameContract } from "@microsoft/fast-components-class-name-contracts-base";
import Foundation, { HandledProps } from "@microsoft/fast-components-foundation-react";
import { classNames, keyCodeEscape, keyCodeTab } from "@microsoft/fast-web-utilities";
import { canUseDOM } from "exenv-es6";
import React from "react";
import { DisplayNamePrefix } from "../utilities";
import { DialogHandledProps, DialogProps, DialogUnhandledProps } from "./dialog.props";
import { isFunction, isNil } from "lodash-es";
import Tabbable from "tabbable";

class Dialog extends Foundation<DialogHandledProps, DialogUnhandledProps, {}> {
    public static defaultProps: Partial<DialogProps> = {
        contentHeight: "480px",
        contentWidth: "640px",
        visible: false,
        managedClasses: {},
    };

    public static displayName: string = `${DisplayNamePrefix}Dialog`;

    protected handledProps: HandledProps<DialogHandledProps> = {
        describedBy: void 0,
        label: void 0,
        labelledBy: void 0,
        contentWidth: void 0,
        contentHeight: void 0,
        modal: void 0,
        managedClasses: void 0,
        onDismiss: void 0,
        visible: void 0,
    };

    private rootElement: React.RefObject<HTMLDivElement> = React.createRef<
        HTMLDivElement
    >();

    /**
     * Renders the component
     */
    public render(): React.ReactElement<HTMLDivElement> {
        const {
            dialog_positioningRegion,
            dialog_contentRegion,
        }: DialogClassNameContract = this.props.managedClasses;

        return (
            <div
                ref={this.rootElement}
                {...this.unhandledProps()}
                className={this.generateClassNames()}
                aria-hidden={!this.props.visible}
            >
                <div className={classNames(dialog_positioningRegion)}>
                    {this.renderModalOverlay()}
                    <div
                        role="dialog"
                        tabIndex={-1}
                        className={classNames(dialog_contentRegion)}
                        style={{
                            height: this.props.contentHeight,
                            width: this.props.contentWidth,
                        }}
                        aria-describedby={this.props.describedBy}
                        aria-labelledby={this.props.labelledBy}
                        aria-label={this.props.label}
                    >
                        {this.props.children}
                    </div>
                </div>
            </div>
        );
    }

    /**
     * React life-cycle method
     */
    public componentDidMount(): void {
        if (canUseDOM()) {
            if (this.shouldAddKeyListener(this.props)) {
                document.addEventListener("keydown", this.handleDocumentKeyDown);
            }
            if (this.props.modal) {
                document.addEventListener("focusin", this.handleDocumentFocus);
                if (this.shouldForceFocus(document.activeElement)) {
                    this.focusOnFirstElement();
                }
            }
        }
    }

    /**
     * React life-cycle method
     */
    public componentDidUpdate(prevProps: Partial<DialogHandledProps>): void {
        if (canUseDOM()) {
            if (!prevProps.modal && this.props.modal) {
                document.addEventListener("focusin", this.handleDocumentFocus);
                this.focusOnFirstElement();
            } else if (prevProps.modal && !this.props.modal) {
                document.removeEventListener("focusin", this.handleDocumentFocus);
            }

            if (
                !this.shouldAddKeyListener(prevProps) &&
                this.shouldAddKeyListener(this.props)
            ) {
                document.addEventListener("keydown", this.handleDocumentKeyDown);
            } else if (
                this.shouldAddKeyListener(prevProps) &&
                !this.shouldAddKeyListener(this.props)
            ) {
                document.removeEventListener("keydown", this.handleDocumentKeyDown);
            }
        }
    }

    /**
     * React life-cycle method
     */
    public componentWillUnmount(): void {
        if (canUseDOM()) {
            if (this.shouldAddKeyListener(this.props)) {
                document.removeEventListener("keydown", this.handleDocumentKeyDown);
            }

            if (this.props.modal) {
                document.removeEventListener("focusin", this.handleDocumentFocus);
            }
        }
    }

    /**
     * Generates class names
     */
    protected generateClassNames(): string {
        return super.generateClassNames(classNames(this.props.managedClasses.dialog));
    }

    /**
     * Renders the modal overlay
     */
    private renderModalOverlay(): React.ReactElement<HTMLDivElement> {
        if (!this.props.modal) {
            return;
        }

        return (
            <div
                className={classNames(this.props.managedClasses.dialog_modalOverlay)}
                onClick={this.checkForSoftDismiss}
                onTouchStart={this.checkForSoftDismiss}
                role={"presentation"}
                tabIndex={-1}
                style={{
                    touchAction: "none",
                }}
            />
        );
    }

    /**
     * Check if props demand a key listener
     */
    private shouldAddKeyListener = (props: DialogProps): boolean => {
        if (props.modal || props.onDismiss) {
            return true;
        }
        return false;
    };

    /**
     * handles document key down events
     */
    private handleDocumentKeyDown = (event: KeyboardEvent): void => {
        if (!event.defaultPrevented && this.props.visible) {
            switch (event.keyCode) {
                case keyCodeEscape:
                    this.checkForSoftDismiss(event);
                    break;

                case keyCodeTab:
                    this.handleTabKeyDown(event);
                    break;
            }
        }
    };

    /**
     * Invokes dialog soft dismiss if appropriate
     */
    private checkForSoftDismiss = (
        event: KeyboardEvent | React.MouseEvent | React.TouchEvent
    ): void => {
        if (
            this.props.onDismiss &&
            typeof this.props.onDismiss === "function" &&
            this.props.visible
        ) {
            this.props.onDismiss(event);
        }
    };

    /**
     * process tab key down events
     */
    private handleTabKeyDown = (event: KeyboardEvent): void => {
        if (!this.props.modal) {
            // only handle tab keystrokes when modal
            return;
        }
        const tabbableElements: HTMLElement[] = Tabbable(this.rootElement.current);
        const tabbableElementCount: number = tabbableElements.length;
        if (tabbableElementCount === 0) {
            this.tryFocusOnRootElement();
            event.preventDefault();
            return;
        }
        // intervene in normal tab order for first and last items in list
        if (event.shiftKey && event.target === tabbableElements[0]) {
            tabbableElements[tabbableElementCount - 1].focus();
            event.preventDefault();
        } else if (
            !event.shiftKey &&
            event.target === tabbableElements[tabbableElementCount - 1]
        ) {
            tabbableElements[0].focus();
            event.preventDefault();
        }
    };

    /**
     * forces focus to first tabbable element of modal dialog if document gains focus while dialog is open
     */
    private handleDocumentFocus = (event: FocusEvent): void => {
        if (
            !event.defaultPrevented &&
            this.shouldForceFocus(event.target as HTMLElement)
        ) {
            this.focusOnFirstElement();
            event.preventDefault();
        }
    };

    /**
     * test to avoid forcing focus when focus is already within
     */
    private shouldForceFocus = (currentFocusElement: Element): boolean => {
        if (
            this.props.visible &&
            this.rootElement.current instanceof HTMLElement &&
            !(this.rootElement.current as HTMLElement).contains(currentFocusElement)
        ) {
            return true;
        }
        return false;
    };

    /**
     * focus on first element of tab queue
     */
    private focusOnFirstElement = (): void => {
        if (canUseDOM() && this.rootElement.current instanceof HTMLElement) {
            const tabbableElements: HTMLElement[] = Tabbable(this.rootElement.current);
            if (tabbableElements.length === 0) {
                this.tryFocusOnRootElement();
            } else {
                tabbableElements[0].focus();
            }
        }
    };

    /**
     * if no tabbable elements try to focus root element
     * generally a modal dialog should be expected to have a focusable element
     */
    private tryFocusOnRootElement = (): void => {
        if (this.rootElement.current instanceof HTMLElement) {
            this.rootElement.current.focus();
        }
    };
}

export default Dialog;
export * from "./dialog.props";
export { DialogClassNameContract };

// packages/web-components/fast-components/src/dialog/dialog.ts
import { attr, DOM, FASTElement } from "@microsoft/fast-element";
import { keyCodeEscape, keyCodeTab } from "@microsoft/fast-web-utilities";
import tabbable from "tabbable";

export class Dialog extends FASTElement {
    @attr
    public modal: boolean = true;

    @attr
    public hidden: boolean = false;

    @attr({ attribute: "trap-focus" })
    public trapFocus: boolean = true;

    @attr({ attribute: "aria-describedby" })
    public ariaDescribedby: string;

    @attr({ attribute: "aria-labelledby" })
    public ariaLabelledby: string;

    @attr({ attribute: "aria-label" })
    public ariaLabel: string;

    public dialog: HTMLDivElement;

    private tabbableElements: HTMLElement[];

    private observer: MutationObserver;

    public dismiss(): void {
        this.$emit("dismiss");
    }

    public connectedCallback(): void {
        super.connectedCallback();

        // store references to tabbable elements
        this.tabbableElements = tabbable(this as Element);

        this.observer = new MutationObserver(this.onChildListChange);
        // only observe if nodes are added or removed
        this.observer.observe(this as Element, { childList: true });

        document.addEventListener("keydown", this.handleDocumentKeydown);

        // Ensure the DOM is updated
        // This helps avoid a delay with `autofocus` elements recieving focus
        DOM.queueUpdate(this.trapFocusChanged);
    }

    public disconnectedCallback(): void {
        super.disconnectedCallback();

        // disconnect observer
        this.observer.disconnect();

        // remove keydown event listener
        document.removeEventListener("keydown", this.handleDocumentKeydown);

        // if we are trapping focus remove the focusin listener
        if (this.shouldDialogTrapFocus()) {
            document.removeEventListener("focusin", this.handleDocumentFocus);
        }
    }

    private onChildListChange(
        mutations: MutationRecord[],
        /* eslint-disable-next-line @typescript-eslint/no-unused-vars */
        observer: MutationObserver
    ): void {
        if (mutations!.length) {
            this.tabbableElements = tabbable(this as Element);
        }
    }

    private trapFocusChanged = (): void => {
        if (this.shouldDialogTrapFocus()) {
            // Add an event listener for focusin events if we should be trapping focus
            document.addEventListener("focusin", this.handleDocumentFocus);

            // determine if we should move focus inside the dialog
            if (this.shouldForceFocus(document.activeElement)) {
                this.focusFirstElement();
            }
        } else {
            // remove event listener if we are not trapping focus
            document.removeEventListener("focusin", this.handleDocumentFocus);
        }
    };

    private handleDocumentKeydown = (e: KeyboardEvent): void => {
        if (!e.defaultPrevented && !this.isDialogHidden()) {
            switch (e.keyCode) {
                case keyCodeEscape:
                    this.dismiss();
                    break;

                case keyCodeTab:
                    this.handleTabKeyDown(e);
                    break;
            }
        }
    };

    private handleDocumentFocus = (e: Event): void => {
        if (!e.defaultPrevented && this.shouldForceFocus(e.target as HTMLElement)) {
            this.focusFirstElement();
            e.preventDefault();
        }
    };

    private handleTabKeyDown = (e: KeyboardEvent): void => {
        if (!this.shouldDialogTrapFocus()) {
            return;
        }

        const tabbableElementCount: number = this.tabbableElements.length;

        if (tabbableElementCount === 0) {
            this.dialog.focus();
            e.preventDefault();
            return;
        }

        if (e.shiftKey && e.target === this.tabbableElements[0]) {
            this.tabbableElements[tabbableElementCount - 1].focus();
            e.preventDefault();
        } else if (
            !e.shiftKey &&
            e.target === this.tabbableElements[tabbableElementCount - 1]
        ) {
            this.tabbableElements[0].focus();
            e.preventDefault();
        }
    };

    /**
     * focus on first element of tab queue
     */
    private focusFirstElement = (): void => {
        if (this.tabbableElements.length === 0) {
            this.dialog.focus();
        } else {
            this.tabbableElements[0].focus();
        }
    };

    /**
     * we should only focus if focus has not already been brought to the dialog
     */
    private shouldForceFocus = (currentFocusElement: Element | null): boolean => {
        return !this.isDialogHidden() && !this.contains(currentFocusElement);
    };

    /**
     * TODO: Issue #2742 - https://github.com/microsoft/fast-dna/issues/2742
     * This is a placeholder function to check if the hidden attribute is present
     * Currently there is not support for boolean attributes.
     * Once support is added, we will simply use this.hidden.
     */
    private isDialogHidden(): boolean {
        return typeof this.hidden !== "boolean";
    }

    /**
     * TODO: Issue #2742 - https://github.com/microsoft/fast-dna/issues/2742
     * This is a placeholder function to check if the trapFocus attribute is present
     * Currently there is not support for boolean attributes.
     * Once support is added, we will simply use this.trapFocus.
     */
    private shouldDialogTrapFocus(): boolean {
        return typeof this.trapFocus === "boolean";
    }
}
